CREATE DATABASE reddog;
USE reddog;
CREATE TABLE transacoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    ip VARCHAR(50) NOT NULL,
    risco VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);